import Config

# Configure your database
# config :ex_sd, ExSd.Repo,
#   username: "postgres",
#   password: "postgres",
#   hostname: "localhost",
#   database: "ex_sd_dev",
#   stacktrace: true,
#   show_sensitive_data_on_connection_error: true,
#   pool_size: 10
config :ex_sd, ExSd.Repo, database: "app_config/database_dev.db"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :ex_sd, ExSdWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "DF/ywuXdpVxNQVPiPlZhoS7kUmRC4Cj/TCz8hAxzv2JSm30emKVV4tTm4mq3yC7r",
  watchers: [
    # esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    # tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]},
    node: [
      "../assets/node_modules/vite/bin/vite.js",
      "--config",
      "../assets/vitest.config.ts",
      cd: "assets"
    ]
  ]

config :ex_sd, :auto_client_base_url, "http://localhost:7860"
config :ex_sd, :comfy_client_base_url, "http://localhost:8188"
# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ex_sd, ExSdWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ex_sd_web/(live|views)/.*(ex)$",
      ~r"lib/ex_sd_web/templates/.*(eex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :ex_sd, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
